-- Harbor — operator / commerce tables (admin-only data)

create type public.customer_status as enum ('lead', 'scheduled', 'installed');
create type public.pairing_status as enum ('pending', 'paired');
create type public.plus_plan as enum ('monthly', 'annual');
create type public.referral_status as enum ('pending', 'contacted', 'converted', 'declined');

-- ── builds (the product line) ────────────────────────────────────────────────
create table public.builds (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  screen_size text,
  tablet_model text,
  standard_price numeric(10, 2) not null default 0,
  founder_price numeric(10, 2) not null default 0,
  is_default boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── build_supplies (the kit per build) ───────────────────────────────────────
create table public.build_supplies (
  id uuid primary key default gen_random_uuid(),
  build_id uuid not null references public.builds (id) on delete cascade,
  item text not null,
  vendor text not null default 'Amazon',
  url text,                          -- product URL or Amazon search term
  unit_cost numeric(10, 2) not null default 0,
  quantity int not null default 1,
  optional boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index build_supplies_build_idx on public.build_supplies (build_id);

-- ── inventory (optional parts tracking) ──────────────────────────────────────
create table public.inventory (
  id uuid primary key default gen_random_uuid(),
  part_name text not null,
  on_hand_qty int not null default 0,
  reorder_threshold int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── customers & installs ─────────────────────────────────────────────────────
create table public.customers (
  id uuid primary key default gen_random_uuid(),
  household_id uuid references public.households (id) on delete set null,
  name text not null,
  email text,
  phone text,
  build_id uuid references public.builds (id) on delete set null,
  status public.customer_status not null default 'lead',
  install_date date,
  install_fee numeric(10, 2),
  founder_number int,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customers_founder_number_range
    check (founder_number is null or (founder_number between 1 and 15))
);
-- Founder numbers are unique when assigned (the 15-spot program).
create unique index customers_founder_number_uniq
  on public.customers (founder_number)
  where founder_number is not null;

-- ── referrals ────────────────────────────────────────────────────────────────
create table public.referrals (
  id uuid primary key default gen_random_uuid(),
  referring_customer_id uuid references public.customers (id) on delete cascade,
  referred_name text not null,
  referred_contact text,
  status public.referral_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index referrals_referrer_idx on public.referrals (referring_customer_id);

-- ── plus_subscriptions ───────────────────────────────────────────────────────
create table public.plus_subscriptions (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null unique references public.households (id) on delete cascade,
  stripe_customer_id text,
  stripe_subscription_id text,
  status text not null default 'inactive',  -- mirrors Stripe subscription status
  plan public.plus_plan,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── device_pairings (kiosk binding) ──────────────────────────────────────────
create table public.device_pairings (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  code text not null unique,         -- short pairing code generated by admin
  device_secret uuid,                -- issued once at pair time; kiosk credential
  device_label text,
  status public.pairing_status not null default 'pending',
  paired_at timestamptz,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index device_pairings_household_idx on public.device_pairings (household_id);
create unique index device_pairings_secret_uniq
  on public.device_pairings (device_secret)
  where device_secret is not null;

-- ── waitlist (public Founding Family signups) ────────────────────────────────
create table public.waitlist (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  town text,
  kids_count int,
  created_at timestamptz not null default now()
);
