-- Skipper's AI thought-bubble lines — per-child-per-day cache.
--
-- The Lantern's sailboat buddy "thinks" short, kid-safe lines (motivation, tips, jokes, mindful notes)
-- generated by /api/ai/skipper. This table caps paid AI generation to ONCE PER CHILD PER DAY: the route
-- serves a cached batch if one exists for (child_id, date), otherwise atomically CLAIMS the slot (unique
-- PK) so exactly one request calls the model — even across multiple devices, retry storms, or a failing
-- key. Backstops the device's own once/day IndexedDB cache.
--
-- RLS is ENABLED with NO policies: anon/authenticated are denied entirely. The ONLY accessor is the
-- device-secret-validated /api/ai/skipper route via the service-role (admin) client, which bypasses RLS.

create table if not exists public.ai_skipper_batches (
  child_id uuid not null,
  date text not null,
  household_id uuid not null,
  lines jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  primary key (child_id, date)
);

alter table public.ai_skipper_batches enable row level security;

comment on table public.ai_skipper_batches is 'Per-child-per-day cache of Skipper AI thought-bubble lines. Caps paid AI generation to once/child/day (server-side backstop to the device''s own once/day cache). Written ONLY by the device-secret-validated /api/ai/skipper route via the service role; RLS is enabled with no policies so anon/authenticated access is denied entirely.';
